export interface AiEnv { AI_API_KEY?: string; AI_MODEL?: string; AI_EMBEDDING_MODEL?: string; AI_API_BASE?: string; }
export function aiEnabled(env: AiEnv): boolean { return Boolean(env.AI_API_KEY); }

export interface AiEvidence { id:string; title:string; summary:string; category:string; sourceUrl:string; dueAt?:string|null; startsAt?:string|null; }
export interface GroundedAnswer { answer:string; citations:string[]; }
interface GeminiResponse { candidates?: Array<{content?:{parts?:Array<{text?:string}>}}> }
interface EmbeddingResponse { embeddings?: Array<{values?:number[]}> }
const baseUrl=(env:AiEnv)=>(env.AI_API_BASE??'https://generativelanguage.googleapis.com/v1beta').replace(/\/$/,'');
async function request(env:AiEnv,model:string,method:string,body:Record<string,unknown>):Promise<unknown>{
 if(!env.AI_API_KEY) throw new Error('AI is not configured');
 const r=await fetch(baseUrl(env)+'/models/'+encodeURIComponent(model)+':'+method,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':env.AI_API_KEY},body:JSON.stringify(body)});
 if(!r.ok) throw new Error('AI provider returned HTTP '+r.status); return r.json();
}
function textOf(v:unknown){const d=v as GeminiResponse;return d.candidates?.[0]?.content?.parts?.map(p=>p.text??'').join('').trim()??'';}
export function extractJsonObject(text:string):unknown{const t=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a<0||b<=a)throw new Error('AI did not return JSON');return JSON.parse(t.slice(a,b+1)) as unknown;}
export function validateGroundedAnswer(v:unknown,e:AiEvidence[]):GroundedAnswer{if(!v||typeof v!=='object')throw new Error('Invalid AI answer');const x=v as {answer?:unknown;citations?:unknown};if(typeof x.answer!=='string'||!x.answer.trim())throw new Error('AI answer is empty');if(!Array.isArray(x.citations)||!x.citations.length)throw new Error('AI answer has no citations');const allowed=new Set(e.map(x=>x.id));const c=x.citations.filter((id):id is string=>typeof id==='string'&&allowed.has(id));if(c.length!==x.citations.length)throw new Error('AI cited evidence outside supplied set');return {answer:x.answer.trim(),citations:c};}
export function buildGroundedPrompt(task:string,e:AiEvidence[]):string{return ['You are the VGU Signal explanation layer.','The supplied evidence is the only factual authority.','Do not invent, infer, or fill missing university facts.','If evidence does not answer the question, say the verified archive does not establish it.','Never create a deadline, date, fee, policy, event, or official claim absent from evidence.','Return JSON: {answer:string,citations:string[]}. citations must be supplied evidence IDs.','Student request: '+task,'Verified evidence:',...e.map(x=>'[EVIDENCE '+x.id+'] '+x.title+' | '+x.category+' | '+x.summary+' | source='+x.sourceUrl)].join('\n');}
export async function groundedAnswer(env:AiEnv,task:string,e:AiEvidence[]):Promise<GroundedAnswer>{if(!e.length)throw new Error('No verified evidence');const v=await request(env,env.AI_MODEL??'gemini-2.5-flash-lite','generateContent',{contents:[{parts:[{text:buildGroundedPrompt(task,e)}]}],generationConfig:{temperature:0.1,responseMimeType:'application/json'}});return validateGroundedAnswer(extractJsonObject(textOf(v)),e);}
export async function embedText(env:AiEnv,text:string):Promise<number[]>{const v=await request(env,env.AI_EMBEDDING_MODEL??'gemini-embedding-2','embedContent',{content:{parts:[{text:text.slice(0,12000)}]},outputDimensionality:768});const x=(v as EmbeddingResponse).embeddings?.[0]?.values;if(!x?.length)throw new Error('AI provider returned no embedding');return x;}
export function cosineSimilarity(a:number[],b:number[]):number{if(!a.length||a.length!==b.length)return 0;let d=0,an=0,bn=0;for(let i=0;i<a.length;i++){d+=a[i]*b[i];an+=a[i]*a[i];bn+=b[i]*b[i];}return an&&bn?d/Math.sqrt(an*bn):0;}
export function renderGroundedAnswer(r:GroundedAnswer,e:AiEvidence[]):string{const m=new Map(e.map(x=>[x.id,x]));const s=r.citations.map(id=>{const x=m.get(id);return x?'• <a href="'+x.sourceUrl+'">'+x.title+'</a>':''}).filter(Boolean);return '<b>AI-assisted answer</b>\n\n'+r.answer+'\n\n<b>Verified evidence</b>\n'+s.join('\n')+'\n\n<i>AI only explains verified VGU evidence; it does not create or verify university facts.</i>';}